addresses = [
    "Rua Carlos Barbosa, 22, Capão da Canoa, RS, Brazil",
    "Rua Honório Ferreira da Silva, 2443, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1182, Capão da Canoa, RS, Brazil",
    "Rua da Brigada, 898, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Seis, 304, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua da Alegria, 119, Capão da Canoa, RS, Brazil",
    "Rua Dona Amália, 830, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Deodoro Pacheco, 419, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua General Osório, 690, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua dos Antúrios, 4110, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Rosa, 12, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Gideões Missionários, 715, Capão da Canoa, RS, Brazil",
    "Rua Guilherme Guitman, 1323, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Cinco, 289, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Santana, 102, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Paulina Valim Dariva, 81, Capão da Canoa, RS, Brazil",
    "Rua João Cristiano, 96, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua dos Cravos, 3616, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida Ari Silveira de Souza, 532, Capão da Canoa, RS, Brazil",
    "Rua Sepé, 2500, Centro, Capão da Canoa, RS, Brazil",
    "Rua Santa Elizabeth, 1218, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Antônio Prado, 3058, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Leopoldo Franklin Marques da Rosa, 67, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Zero, 115, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Mané Leandro, 1470, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Mané Leandro, 1470, Capão da Canoa, RS, Brazil",
    "Rua Dilmer Schneider, 1240, Araçá, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 2720, Centro, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Nove, 292, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Araraquara, 285, Praia Guarani, Capão da Canoa, RS, Brazil",
    "Rua Rui Barbosa, 279, Guarani, Capão da Canoa, RS, Brazil",
    "Rua José Bonifácio, 60, Praia Guarani, Capão da Canoa, RS, Brazil",
    "Rua Honório Germano, 1177, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Paulo Porcher, 1368, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Alfa do Centauro, 841, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua São Marcos, 1431, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Estrada RS 407, 6529, Morro Alto, Capão da Canoa, RS, Brazil",
    "Rua Getúlio Vargas, 170, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Inácio Barcellos dos Anjos, 39, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Honduras, 592, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Dilmer Schneider, 960, Capão da Canoa, RS, Brazil",
    "Avenida General Osório, 608, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Valdomiro Cândido dos Reis, 1343, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 1443, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Dez, 328, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Goiás, 121, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Getúlio Vargas, 395, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1182, Capão da Canoa, RS, Brazil",
    "Avenida Parque Três, 605, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1326, Capão da Canoa, RS, Brazil",
    "Rua São Bartolomeu, 259, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Ubirajara, 281, Capão da Canoa, RS, Brazil",
    "Rua Peri, 4390, Girassol, Capão da Canoa, RS, Brazil",
    "Rua Júlio de Castilhos, 858, Capão da Canoa, RS, Brazil",
    "Travessa Jovelina da Silva Matos, 271, Capão da Canoa, RS, Brazil",
    "Rua João Pedro, 48, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua João Pretto, 48, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Santana, 305, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Rudá, 1065, Capão da Canoa, RS, Brazil",
    "Rua Iracema, 164, Girassol, Capão da Canoa, RS, Brazil",
    "Rua Faustino João Pereira, 965, Capão da Canoa, RS, Brazil",
    "Rua Reginaldo Alcides Machado, 426, Capão da Canoa, RS, Brazil",
    "Rua Honório Ferreira da Silva, Capão da Canoa, RS, Brazil",
    "Rua Honório Ferreira da Silva, Capão da Canoa, RS, Brazil",
    "Rua Anchova, 976, Capão da Canoa, RS, Brazil",
    "Rua Nicarágua, 1038, Capão da Canoa, RS, Brazil",
    "Rua Manoel Timóteo Marques, 99, Capão da Canoa, RS, Brazil",
    "Rua Vinte e Quatro, 1413, Capão da Canoa, RS, Brazil",
    "Rua Paulo Porcher, 1380, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua da Alegria, 137, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Avenida Ubatuba de Farias, 1205, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Âmbar, 123, Capão da Canoa, RS, Brazil",
    "Rua Santa Elizabeth, 866, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Águia Real, 211, Capão da Canoa, RS, Brazil",
    "Rua Águia Real, 211, Capão da Canoa, RS, Brazil",
    "Rua Almirante Tamandaré, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Dois, 242, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 1064, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Manoel Nazário, 88, Capão da Canoa, RS, Brazil",
    "Rua Equador, 309, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Honório Germano, 1791, Capão da Canoa, RS, Brazil",
    "Rua Balduíno Reinaldo de Melo, Capão da Canoa, RS, Brazil",
    "Rua Júlio Ribeiro, 96, Capão da Canoa, RS, Brazil",
    "Rua Rodrigo Bittencourt de Farias, 2096, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Osvaldo Barbosa, 168, Arpoador, Capão da Canoa, RS, Brazil",
    "Rua Jovelina S. Mattos, 134, Capão da Canoa, RS, Brazil",
    "Rua Cesarina Prado Reus, 92, Atlântida, Capão da Canoa, RS, Brazil",
    "Rua Santo Amaro, 1079, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 90, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 661, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua da Pescaria, 434, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Santa Rosa, 1238, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 2121, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Vinte e Nove, 225, Capão da Canoa, RS, Brazil",
    "Rua Amapá, 40, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Nove, 243, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cesarino Padre Reus, 632, Capão da Canoa, RS, Brazil",
    "Rua Estrada Federal, 109, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 2121, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Cesarino Padre Reus, 632, Capão da Canoa, RS, Brazil",
    "Rua Osório Ferreira da Silva, 48, Capão da Canoa, RS, Brazil",
    "Rua Brasília, 1754, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 80, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Saracura, 3104, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Jasmim, 144, Rainha do Mar, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 391, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Gerônimo de Souza, 228, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 1593, Capão da Canoa, RS, Brazil",
    "Avenida José Serafim de Souza, 234, Capão da Canoa, RS, Brazil",
    "Rua das Zínias, 3431, Capão da Canoa, RS, Brazil",
    "Rua Marabá, 1501, Capão da Canoa, RS, Brazil",
    "Rua Dez, 455, Capão da Canoa, RS, Brazil",
    "Rua Honduras, 417, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Dois, 242, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Avenida Ubatuba de Farias, 1398, Zona Nova, Capão da Canoa, RS, Brazil",
    "Avenida Central, 455, Capão da Canoa, RS, Brazil",
    "Rua Carlos Barbosa, 286, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Peri, 865, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua da Pescaria, 223, Capão da Canoa, RS, Brazil",
    "Rua Rio Pardo, 1685, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Vitor, 171, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1182, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1182, Capão da Canoa, RS, Brazil",
    "Avenida Getúlio Vargas, 193, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Gaspar Grizza, 1531, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Alfa do Centauro, 999, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Chapecó, 560, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Maurício de Souza, 361, Capão da Canoa, RS, Brazil",
    "Rua Vinte e Cinco, 2021, Capão da Canoa, RS, Brazil",
    "Rua Valdomiro Cândido dos Reis, 335, Capão da Canoa, RS, Brazil",
    "Rua das Hortênsias, 3533, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 658, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Nove, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1558, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Avenida Ana Paula, 642, Arpoador, Capão da Canoa, RS, Brazil",
    "Rua Equador, 87, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Geloí José da Silva, 261, Capão da Canoa, RS, Brazil",
    "Rua Águia Real, 304, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1558, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Antônio Prado, 3309, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 80, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Peixe Rei, 70, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Saracura, 32, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 890, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Maraguaia, 148, Marina, Capão da Canoa, RS, Brazil",
    "Rua O, 115, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Geloí José da Silva, 300, Guará, Capão da Canoa, RS, Brazil",
    "Avenida Diamante, 859, Capão da Canoa, RS, Brazil",
    "Rua Santa Elizabeth, 2422, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Padre Cesarino Reus, 312, Capão da Canoa, RS, Brazil",
    "Avenida Parque Três, 605, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Valdomiro Cândido dos Reis, 1432, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Três Marias, 966, Capão da Canoa, RS, Brazil",
    "Rua das Hortênsias, 296, Capão da Canoa, RS, Brazil",
    "Rua Dona Amália, 830, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Beta do Centauro, 134, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Panamá, 520, Capão da Canoa, RS, Brazil",
    "Rua Panamá, 122, Capão da Canoa, RS, Brazil",
    "Rua Peixe Rei, 88, Capão da Canoa, RS, Brazil",
    "Rua Panamá, 221, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Panamá, 221, Zona Nova, Capão da Canoa, RS, Brazil",
    "Estrada dos Muller, 501, Capão da Canoa, RS, Brazil",
    "Rua México, 245, Capão da Canoa, RS, Brazil",
    "Rua São Francisco de Assis, 939, Praia do Remanso, Capão da Canoa, RS, Brazil",
    "Rua Peri, 1984, Centro, Capão da Canoa, RS, Brazil",
    "Rua Dez, 1040, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 1196, Capão da Canoa, RS, Brazil",
    "Rua Cinco, 59, Morada do Sol, Capão da Canoa, RS, Brazil",
    "Rua Rio das Contas, 1635, Centro, Capão da Canoa, RS, Brazil",
    "Rua Copo de Leite, 97, Capão da Canoa, RS, Brazil",
    "Rua F, 58, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Equador, 466, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Alfa da Cruz, 1443, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua das Zínias, 343, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Nicarágua, 23, Capão da Canoa, RS, Brazil",
    "Rua Nicarágua, 23, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Rodrigo Bittencourt de Farias, Capão da Canoa, RS, Brazil",
    "Beco São Pedro, 151, Guará, Capão da Canoa, RS, Brazil",
    "Rua dos Lírios, 2, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Caracol, 139, Marina, Capão da Canoa, RS, Brazil",
    "Rua Via Láctea, 712, Arco Iris, Capão da Canoa, RS, Brazil",
    "Travessa São Pedro, 1195, Capão da Canoa, RS, Brazil",
    "Rua Getúlio Vargas, 193, Capão da Canoa, RS, Brazil",
    "Rua Ceci, 3285, Capão da Canoa, RS, Brazil",
    "Rua Nove, 390, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Oito, 155, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua São Francisco de Paula, Capão da Canoa, RS, Brazil",
    "Rua Estrela Polar, 244, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Manoel Alves, 14, Guará, Capão da Canoa, RS, Brazil",
    "Rua das Cravinas, 3033, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Acre, 40, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 94, Capão da Canoa, RS, Brazil",
    "Rua das Rosas, 2411, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Amazonas, 72, Capão da Canoa, RS, Brazil",
    "Rua Imbuia, 154, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 330, Arpoador, Capão da Canoa, RS, Brazil",
    "Rua Santana, 102, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua Cacique, 108, Curumim, Capão da Canoa, RS, Brazil",
    "Rua Luiz Alves Pereira, 2191, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Olmiro Lima, 39, Capão da Canoa, RS, Brazil",
    "Rua Dois, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Oito, 1013, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Rio Comandaí, 2271, Centro, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 174, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 167, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 167, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 509, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua F, 40, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Quatro, 310, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua General Osório, 1644, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Rodrigo Bittencourt de Farias, 1996, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua das Orquídeas, 2822, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 392, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 980, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Cristiano, 80, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Rodrigo Bittencourt de Farias, 2012, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Pará, 110, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Honório Germano, 100, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Manoel Alves, 111, Guará, Capão da Canoa, RS, Brazil",
    "Estrada Federal, 77, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Valdomiro Cândido dos Reis, 1448, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua César Bittencourt, 136, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua das Orquídeas, 2822, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Japajós, 984, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Avenida Beira Mar, 1245, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua da Pescaria, 434, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 978, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 978, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua das Hortênsias, 3080, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 1137, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua dos Lírios, 2802, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Leopoldo Franklin Marques da Rosa, 407, Capão da Canoa, RS, Brazil",
    "Rua J, 59, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Dez, 450, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Lambari, 83, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Dois, 91, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Quatro, 230, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Canela, 21, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Amapá, 100, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Flamboiã, 615, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Rio Novo, 947, Centro, Capão da Canoa, RS, Brazil",
    "Rua Faustino João Pereira, 861, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua da Brigada Militar, 110, Capão da Canoa, RS, Brazil",
    "Rua Paulo Porcher, 924, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Anchovas, 870, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Caxias, 348, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Aratiba, 84, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Acre, 81, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Anchovas, 447, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Dois, 939, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua da Alegria, 142, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Alfa do Centauro, 1016, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 256, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Paulo Porcher, 980, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Júlio de Castilhos, 822, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Aroeira, 2778, Vale Verde, Capão da Canoa, RS, Brazil"
]
