addresses = [
    "Condomínio Caminito, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Paulo Porcher, 72, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Gaspar Grizza, 934, Centro, Capão da Canoa, RS, Brazil",
    "Rua Três Marias, 947, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Ari Silveira de Souza, 839, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Alfa do Centauro, 1020, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua das Margaridas, 3246, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua U, 203, Zona Norte, Capão da Canoa, RS, Brazil",
    "Avenida A, 381, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Luiz Alves Pereira, 1665, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Estrada Federal, 109, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 2014, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Santa Elizabeth, 818, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua das Zínias, 100, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Onze, 220, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Sepé, 1555, Centro, Capão da Canoa, RS, Brazil",
    "Rua L, 20, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua das Tulipas, 2210, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida Parque Três, 677, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua das Papoulas, 3640, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida Flávio Boianovski, 1341, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Caracol, 167, Marina, Capão da Canoa, RS, Brazil",
    "Rua das Camélias, 3018, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Rigel, 90, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Beco da Canopo, 361, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Santo Amaro, 1030, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Lambari, 125, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Peixe Rei, 88, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Antônio Prado, 3225, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Amazonita, 1253, Rainha do Mar, Capão da Canoa, RS, Brazil",
    "Rua das Margaridas, 2618, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Trinta, 97, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua João Alves Viana, 321, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Aratiba, 324, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Amazonas, 23, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Luiz Alves Pereira, 759, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Tainá, 264, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua dos Antúrios, 4035, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Nicarágua, 297, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Pedro Álvares Cabral, 153, Arpoador, Capão da Canoa, RS, Brazil",
    "Rua U, 35, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1513, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua das Margaridas, 2612, Capão Novo, Capão da Canoa, RS, Brazil",
    "Estrada do Mar, 41, Capão da Canoa, RS, Brazil",
    "Rua Papa Terra, 921, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 1069, Arco Iris, Capão da Canoa, RS, Brazil",
    "Avenida Orestes Clemente Serra, 1059, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Albemaran, 58, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Parque Três, 718, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Bitencourt de Farias, 224, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua A, 12, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua A, 12, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Narciso, 3774, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Quarenta, 1722, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Getúlio Vargas, 170, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Osvaldo Bastos, 718, Centro, Capão da Canoa, RS, Brazil",
    "Rua Luiz Alves Pereira, 1414, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Beta do Centauro, 250, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua dos Lírios, 2800, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Moacir, 1724, Centro, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Oito, 1013, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Faisão Dourado, 319, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua das Cravinas, 3459, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Luiz Ferreira da Silva, 311, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Treze, 1000, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Honório Germano, 1370, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua José Raupp, 1670, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Coronel Arlindo de Carvalho, 399, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Falcão Azul, 433, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua K, 20, Bom Jesus, Capão da Canoa, RS, Brazil",
    "Rua Leopoldo Franklin Marcos da Rosa, 472, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Oito, 709, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Cuba, 101, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Santa Elizabeth, 1757, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Falcão Dourado, 98, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua João Prudêncio, 249, Centro, Capão da Canoa, RS, Brazil",
    "Rua Amazonita, 424, Rainha do Mar, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 942, Centro, Capão da Canoa, RS, Brazil",
    "Rua Emboá, 558, Atlântida, Capão da Canoa, RS, Brazil",
    "Rua Cisnei Branco, 419, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Cisnei Branco, 470, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Falcão Azul, 120, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Paulo Teixeira, 967, Guará, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 150, Centro, Capão da Canoa, RS, Brazil",
    "Rua Faisão Dourado, 139, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Acre, 60, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Brasil, 310, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Faustino João Pereira, 101, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua dos Navegantes, Marina, Capão da Canoa, RS, Brazil",
    "Rua O, 168, Praia do Arpoador, Capão da Canoa, RS, Brazil",
    "Rua Brasil, 71, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Jacob Galimberth, 132, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 1827, Capão da Canoa, RS, Brazil",
    "Rua Saturnino Amaro Ramos Pereira, 212, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua O, 168, Praia do Arpoador, Capão da Canoa, RS, Brazil",
    "Rua Quarenta, 1275, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Otávio Rocha, 129, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Avenida Poti, 424, Centro, Capão da Canoa, RS, Brazil",
    "Rua Dilmer Schneider, 937, Araçá, Capão da Canoa, RS, Brazil",
    "Avenida Parque Três, 2699, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 1067, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Orion, 680, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Bom Fim, 346, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Taquari, 650, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Boca de Leão, 3465, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Falcão Azul, 58, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Cuba, 266, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua das Onze Horas, 3, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Flávio Boianovski, 1054, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Canela, 19, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua das Cravinas, 4050, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Alzemiro do Amaral, 189, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua José Serafim de Souza, 216, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Avenida Praia do Barco, 546, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Maquiné, 533, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 754, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Quatorze, 265, Vila Verde, Capão da Canoa, RS, Brazil",
    "Rua H, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Nossa Senhora Aparecida, 1275, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Dois, 1353, Araçá, Capão da Canoa, RS, Brazil",
    "Linha Solidão, 2287, Capão da Canoa, RS, Brazil",
    "Rua Vinte e Nove, 250, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua A, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Dilmer Schneider, 1000, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Inácio Barcellos dos Anjos, 295, Santo Antônio, Capão da Canoa, RS, Brazil",
    "Rua A, 12, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Nove, 292, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Cinco, 89, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Vinte e Nove, 250, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Águia Real, 515, Centro, Capão da Canoa, RS, Brazil",
    "Rua Mané Leandro, 1847, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Nove, 27, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Amazonas, 72, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Um, 1039, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Sete, 370, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Oito, 313, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Quatro, 230, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Sete de Setembro, 2324, Morch, Capão da Canoa, RS, Brazil",
    "Rua Peixe Rei, 100, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Quatro, 271, Morada do Sol, Capão da Canoa, RS, Brazil",
    "Rua Dilmer Schneider, 1093, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Honduras, 471, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Um, 1074, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Seis, 242, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua dos Júlios, 247, Júlios, Capão da Canoa, RS, Brazil",
    "Rua Paraná, 964, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Francisco Manoel da Silva, 342, São Lucas, Capão da Canoa, RS, Brazil",
    "Rua Jacuí, 77, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Nova Bassano, 1176, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Ubirajara, Curumim, Capão da Canoa, RS, Brazil",
    "Rua General Osório, 608, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua dos Crisântemos, 3196, Capão da Canoa, RS, Brazil",
    "Rua Emboá, 558, Atlântida, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Três, 914, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Honório Ferreira da Silva, 448, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Mané Leandro, 195, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Estrada Federal, 77, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua dos Escoteiros, 115, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua das Violetas, 6, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Júlio de Castilhos, 1000, Guarani, Capão da Canoa, RS, Brazil",
    "Rua Júlio de Castilhos, 1000, Guarani, Capão da Canoa, RS, Brazil",
    "Avenida Moab Caldas, 451, Santa Tereza, Capão da Canoa, RS, Brazil",
    "Rua Honório Germano, 1117, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Osmani Veras da Silveira, 528, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua das Petúnias, 53, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida General Osório, 1073, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Júlio de Castilhos, 1614, Arco Iris, Capão da Canoa, RS, Brazil",
    "Avenida Valdomiro Cândido dos Reis, 565, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 1169, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Avenida das Gaivotas, 4285, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Copo de Leite, 3149, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua das Onze Horas, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Cisnei Branco, 542, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Alfa do Centauro, 1995, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Gaspar Grizza, 1895, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 157, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua do Jasmim, 3001, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Boa Vista, 720, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Paraguassu, 2767, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Amazonas, 148, São Manoel, Capão da Canoa, RS, Brazil",
    "Rua Eucalipto, 367, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Bem-te-vi, 4043, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Invasão do Marina Park, 7, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Moacir, 254, Centro, Capão da Canoa, RS, Brazil",
    "Rua Búzios, 182, Atlântida Sul, Capão da Canoa, RS, Brazil",
    "Rua Roraima, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Orestes Clemente Serra, 2097, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua Dorvalino Matos Santos, 28, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Sepé, 1752, Centro, Capão da Canoa, RS, Brazil",
    "Rua Papa Terra, 322, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Avenida Brasil, 301, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Três de Maio, 547, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Ari Silveira de Souza, 687, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Nicarágua, 296, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Nadir Moura, 1139, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Trinta e Um, 1398, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Arlindo de Carvalho, 818, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Manoel Quadros, 1454, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Tapajós, 226, Centro, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 661, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Linha Bernardes, 3102, Vila Nova, Capão da Canoa, RS, Brazil",
    "Rua Paulina Valim Dariva, 663, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua da Pescaria, 1194, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua dos Gerânios, 10, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida Orestes Clemente Serra, 1238, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 16, Praia do Remanso, Capão da Canoa, RS, Brazil",
    "Rua Rio Novo, 1830, Sambaqui, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, Centro, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 942, Centro, Capão da Canoa, RS, Brazil",
    "Rua Onze Horas, 7, Capão Novo, Capão da Canoa, RS, Brazil",
    "Avenida Paraguassu, 3664, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Mané Leandro, 355, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua das Rosas, 2511, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua General Osório, 592, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua das Íris, 65, Noiva do Mar, Capão da Canoa, RS, Brazil",
    "Rua Rio Camisas, 407, Centro, Capão da Canoa, RS, Brazil",
    "Rua Carumbá, 159, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Hoffmann, 9, Arroio Teixeira, Capão da Canoa, RS, Brazil",
    "Rua Honório Ferreira da Silva, 2423, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1052, Zona Nova, Capão da Canoa, RS, Brazil",
    "Rua Begônias, 3789, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Saracura, 3220, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Brasil, 160, Zona Norte, Capão da Canoa, RS, Brazil",
    "Avenida Central, 326, Araçá, Capão da Canoa, RS, Brazil",
    "Rua Albatroz, 3737, Capão Novo, Capão da Canoa, RS, Brazil",
    "Rua Cinquenta e Oito, 241, Parque Antártica, Capão da Canoa, RS, Brazil",
    "Rua Sepé, 1555, Centro, Capão da Canoa, RS, Brazil",
    "Alameda Safira, 1831, Rainha do Mar, Capão da Canoa, RS, Brazil",
    "Rua das Aroeiras, 306, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Acre, 81, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 15, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua São Pedro, 15, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Silveira de Souza, 938, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua José Galiardo, 341, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua das Margaridas, 310, Noiva do Mar, Capão da Canoa, RS, Brazil",
    "Rua Divisória, 1335, Novo Horizonte, Capão da Canoa, RS, Brazil",
    "Rua Chapecó, 460, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 2014, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Santa Rosa, 1120, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 1064, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Pará, 63, Quero Quero, Capão da Canoa, RS, Brazil",
    "Rua Nossa Senhora Aparecida, 2715, São Jorge, Capão da Canoa, RS, Brazil",
    "Rua R, 180, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Dez de Setembro, 554, Vale Verde, Capão da Canoa, RS, Brazil",
    "Rua Falcão Azul, 225, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Falcão Azul, 225, Figueirinha, Capão da Canoa, RS, Brazil",
    "Rua Cação, 147, Jardim Beira Mar, Capão da Canoa, RS, Brazil",
    "Rua Canopo, 422, Arco Iris, Capão da Canoa, RS, Brazil",
    "Rua Peixe Rei, 34, Zona Norte, Capão da Canoa, RS, Brazil",
    "Rua Guaraci, 3223, Navegantes, Capão da Canoa, RS, Brazil",
    "Rua A, 62, Praia do Barco, Capão da Canoa, RS, Brazil",
    "Rua Gaspar Grizza, 1045, Santa Luzia, Capão da Canoa, RS, Brazil",
    "Rua Jaloé José da Silva, 300, Atlântida, Capão da Canoa, RS, Brazil"
]